#!/bin/sh

alias find=${FIND:-find}

cd ..
res=$(find .fixture/r -exec false {} + -print)
status=$?
echo $res
case $(echo "$res" | sort) in
  ('.fixture/r
.fixture/r/1
.fixture/r/1/3
.fixture/r/2') ;;
  (*) exit 9 ;;
esac
case $status in
  (0) exit 8 ;;
  (*) ;;
esac
exit 0
