#!/bin/sh

alias find=${FIND:-find}

cd ..
# Like a slow '-type f'
res=$(find .fixture/r -exec test -f {} \; -print | sort)
echo $res
case $res in
  ('.fixture/r/1/3
.fixture/r/2') ;;
  (*) exit 9 ;;
esac
